language: node_js
node_js:
  - "14"
  - "node"
git:
  depth: 5
before_install:
  - npm i -g yarn
install:
  - yarn install
  - yarn start:prod
script:
  - yarn run test
after_success: yarn run test:cov